[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.virtualenv", "file", "postgresql"]

[phases.install]
cmds = [
    "cd backend && python -m venv /opt/venv",
    "cd backend && /opt/venv/bin/pip install --upgrade pip",
    "cd backend && /opt/venv/bin/pip install -r requirements.txt"
]

# Explicitly empty the build phase to avoid npm run build errors
[phases.build]
cmds = []

[start]
cmd = "cd backend && /opt/venv/bin/uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000}"
