[phases.setup]
nixPkgs = ["nodejs_20", "python311", "python311Packages.pip", "file"]

[phases.install]
cmds = [
    "npm install",
    "cd backend && python -m venv /opt/venv && /opt/venv/bin/pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "npm run build"
]

[start]
cmd = "node serve.js"
